#!/bin/bash
# Script para abrir vManage GUI y guiar en la exploración

VMANAGE_HOST=$(grep VMANAGE_HOST .env | cut -d '=' -f2)

echo "======================================================================"
echo "🌐 GUÍA: ACCESO A VMANAGE GUI PARA FLUJOS DETALLADOS"
echo "======================================================================"
echo ""
echo "1️⃣  ACCESO A DOCUMENTACIÓN DE API"
echo "----------------------------------------------------------------------"
echo "   Abre en tu navegador:"
echo "   https://$VMANAGE_HOST/apidocs"
echo ""
echo "   Busca endpoints relacionados con:"
echo "   - 'dpi' (Deep Packet Inspection)"
echo "   - 'applications'"
echo "   - 'flows'"
echo "   - 'statistics'"
echo ""
echo ""
echo "2️⃣  ACCESO A MONITOR DE APLICACIONES"
echo "----------------------------------------------------------------------"
echo "   URL: https://$VMANAGE_HOST"
echo "   Usuario: $(grep VMANAGE_USERNAME .env | cut -d '=' -f2)"
echo "   Password: (el configurado en .env)"
echo ""
echo "   Navegación:"
echo "   Monitor → Applications → Application-Aware Routing"
echo ""
echo "   O también:"
echo "   Monitor → Devices → [Selecciona un router] → Real Time"
echo "   → DPI → Applications"
echo ""
echo ""
echo "3️⃣  CAPTURAR ENDPOINTS REALES CON DEVTOOLS"
echo "----------------------------------------------------------------------"
echo "   a) Abre Chrome DevTools (F12)"
echo "   b) Ve a la pestaña 'Network'"
echo "   c) Filtra por 'XHR' o 'Fetch'"
echo "   d) Navega a Monitor → Applications"
echo "   e) Selecciona una aplicación (ej: W3-Relaciones-familiare)"
echo ""
echo "   Verás peticiones como:"
echo "   - GET /dataservice/data/device/dpi?..."
echo "   - POST /dataservice/statistics/dpi/aggregation"
echo "   - GET /dataservice/monitor/network/...?query=..."
echo ""
echo "   Copia las URLs completas y guárdalas en:"
echo "   ~/Documentos/serv_mcp/endpoints_capturados.txt"
echo ""
echo ""
echo "4️⃣  EXPORTAR DATOS MANUALMENTE (TEMPORAL)"
echo "----------------------------------------------------------------------"
echo "   Mientras implementamos la API, puedes:"
echo ""
echo "   a) En vManage GUI, filtra por aplicación sospechosa"
echo "   b) Clic en 'Export' o botón de descarga"
echo "   c) Guarda CSV con los flujos"
echo "   d) El CSV incluirá:"
echo "      - Source IP (usuarios)"
echo "      - Destination IP (servidores)"
echo "      - Application"
echo "      - Bytes"
echo "      - Site"
echo ""
echo ""
echo "5️⃣  EJEMPLO: BUSCAR W3-Relaciones-familiare"
echo "----------------------------------------------------------------------"
echo "   1. Login en vManage GUI"
echo "   2. Monitor → Applications"
echo "   3. En el filtro de búsqueda, escribe: 'W3-Relaciones'"
echo "   4. Verás tabla con columnas:"
echo "      - Application: W3-Relaciones-familiare"
echo "      - Source: IP origen (10.x.x.x)"
echo "      - Destination: IP destino (externa)"
echo "      - Site: Nombre del sitio"
echo "      - Bytes: Uso"
echo "   5. Clic en 'Export' para descargar"
echo ""
echo ""
echo "======================================================================"
echo "📝 PRÓXIMOS PASOS TÉCNICOS"
echo "======================================================================"
echo ""
echo "Una vez captures los endpoints desde DevTools:"
echo ""
echo "1. Guarda las URLs en: endpoints_capturados.txt"
echo "2. Ejecuta: python crear_funcion_flujos.py"
echo "3. Eso generará automáticamente la función para el MCP server"
echo ""
echo "Mientras tanto, usa la GUI para análisis inmediato."
echo ""
echo "¿Deseas abrir vManage en el navegador ahora? (s/n)"
read -r respuesta

if [[ "$respuesta" == "s" || "$respuesta" == "S" ]]; then
    echo ""
    echo "🌐 Abriendo vManage en navegador..."
    xdg-open "https://$VMANAGE_HOST" 2>/dev/null || \
    open "https://$VMANAGE_HOST" 2>/dev/null || \
    echo "   Abre manualmente: https://$VMANAGE_HOST"
fi

echo ""
echo "✅ Guía completa mostrada"
echo ""
