#!/bin/bash

echo "============================================================"
echo "  📥 INSTALACIÓN DE CLAUDE DESKTOP PARA LINUX"
echo "============================================================"
echo ""
echo "Claude Desktop es GRATUITO y te permitirá:"
echo "  • Hacer preguntas en lenguaje natural"
echo "  • Usar el servidor MCP automáticamente"
echo "  • Consultar vManage conversacionalmente"
echo ""
echo "------------------------------------------------------------"
echo "  PASOS PARA INSTALAR:"
echo "------------------------------------------------------------"
echo ""
echo "1. Abre tu navegador y ve a:"
echo "   https://claude.ai/download"
echo ""
echo "2. Descarga la versión para Linux:"
echo "   • Ubuntu/Debian: Archivo .deb"
echo "   • Otras distros: AppImage"
echo ""
echo "3. Instala el paquete:"
echo "   sudo dpkg -i claude-desktop_*.deb"
echo "   # O ejecuta el AppImage directamente"
echo ""
echo "4. El servidor MCP ya está configurado en:"
echo "   ~/.config/Claude/claude_desktop_config.json"
echo ""
echo "5. Abre Claude Desktop y pregunta:"
echo "   \"Lista todos mis dispositivos SD-WAN\""
echo "   \"¿Hay alarmas críticas?\""
echo "   \"Muéstrame el estado del dispositivo 10.1.1.1\""
echo ""
echo "============================================================"
echo ""
echo "💡 ALTERNATIVA: ¿Quieres descargar Claude Desktop ahora?"
echo ""
read -p "¿Abrir la página de descarga? (s/n): " respuesta

if [[ "$respuesta" =~ ^[Ss]$ ]]; then
    echo ""
    echo "🌐 Abriendo navegador..."
    xdg-open "https://claude.ai/download" 2>/dev/null || echo "Abre manualmente: https://claude.ai/download"
else
    echo ""
    echo "👍 Puedes descargar Claude Desktop cuando quieras desde:"
    echo "   https://claude.ai/download"
fi

echo ""
echo "============================================================"
